name: 'Download artifact'
description: 'Download artifact from GitHub'
inputs:
  name:
    description: 'Name of the artifact to download'
    required: true
    type: string
    default: 'blob-report'
  path:
    description: 'Directory with downloaded artifacts'
    required: true
    type: string
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/github-script@v6
      with:
        script: |
          console.log(`downloading artifacts for workflow_run: ${context.payload.workflow_run.id}`);
          console.log(`workflow_run: ${JSON.stringify(context.payload.workflow_run, null, 2)}`);
          const { data } = await github.rest.actions.listWorkflowRunArtifacts({
            ...context.repo,
            run_id: context.payload.workflow_run.id
          });
          console.log('total = ', data.total_count);
          const name = '${{ inputs.name }}';
          const artifacts = data.artifacts.filter(a => a.name.startsWith(name));
          for (const artifact of artifacts) {
            const result = await github.rest.actions.downloadArtifact({
              ...context.repo,
              artifact_id: artifact.id,
              archive_format: 'zip'
            });
            console.log('downloaded artifact', result);
            const fs = require('fs');
            fs.writeFileSync(`${artifact.name}.zip`, Buffer.from(result.data));
          }
    - name: Unzip artifacts
      shell: bash
      run: |
        unzip ${{ inputs.name }}*.zip -d ${{ inputs.path }}
        ls -R ${{ inputs.path }}
