name: Comment on PR

on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit = context.sha || '0a71a4f47c8b45bda6793a456b7dda069bb2b8eb';
            console.log('Commit: ', commit);
            console.log('context.repo: ', context.repo);
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: commit,
            });
            if (prs.length === 0)
              core.error('No pull request found for commit');
            const prNumber = prs[0].number;
            console.log('PR number: ', prNumber);
            const resp = await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: 'Test comment ' + commit,
            });
            console.log(JSON.stringify(resp, null, 2));
