name: Comment on PR

on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const commit = github.context.sha || '0a71a4f47c8b45bda6793a456b7dda069bb2b8eb';

            console.log('Commit: ', commit);
            console.log('github.context.repo: ', github.context.repo);
            console.log('github.context.owner: ', github.context.owner);

            const { data: prs } = await octokit.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: github.context.repo,
              repo: github.context.owner,
              commit_sha: commit,
            });
            if (prs.length === 0)
              core.error('No pull request found for commit');
            const prNumber = prs[0].number;
            console.log('PR number: ', prNumber);
            const resp = await octokit.rest.issues.createComment({
              owner: github.context.repo,
              repo: github.context.owner,
              issue_number: prNumber,
              body: 'Test comment ' + commit,
            });
            console.log(JSON.stringify(resp, null, 2));
