name: Comment on PR

on:
  push:

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prList = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })
            console.log('result', JSON.stringify(prList, null, 2))
            if (prList.data.length !== 0) {
              console.log('prList.data[0].number', prList.data[0].number)
              return prList.data[0].number
            } else {
              return 0
            }

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = ${{ steps.pr.outputs.result }};
            if (prNumber !== 0) {
              const result = await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for your pull request!'
              })
              console.log('result', JSON.stringify(result, null, 2))
            }
