name: Comment on PR

on:
  push:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param: ['value1', 'value2']
        include:
          - param: value3
            channel: chromium-tip-of-tree

    steps:
      - name: Check matrix param
        run: echo "The matrix param is MY_VAR2=$MY_VAR2"
        env:
          MY_VAR2: ${{ (matrix.channel && format('prefix {0}', matrix.channel)) || 'empty' }}
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.sha,
            });
            if (prs.length === 0) {
              core.error('No pull request found for commit ' + context.sha);
              return;
            }
            core.info('Adding comment to: ' + prs[0].html_url);
            const { data: response } = await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prs[0].number,
              body: 'Test comment ' + new Date(),
            });
            core.info('Posted comment: ' + response.html_url);
