name: Print browser installation paths
on:
  workflow_dispatch:
jobs:
  pint-paths:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: microsoft/playwright
        path: playwright
        sparse-checkout: |
          packages/playwright-dashboard/src/
    - name: Print sparse checkout
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cd playwright
        find .

    - name: Print environment
      if: runner.os != 'Windows'
      shell: bash
      run: |
        env
    - name: Dump env using cmd
      if: runner.os == 'Windows'
      shell: cmd
      run: set
