name: Print browser installation paths
on:
  workflow_dispatch:
jobs:
  pint-paths:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Print firefox location
      shell: bash
      run: |
        echo "OS: $RUNNER_OS"
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          which firefox || echo "Firefox not found"
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          cmd.exe /C "where firefox" || echo "Firefox not found"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          ls -l /Applications/Firefox.app/Contents/MacOS/firefox || echo "Firefox not found"
        fi
