name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        shard: [1/2, 2/2]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      run: npx playwright test --shard ${{ matrix.shard }}

    - name: Upload artifact to Azure Blob Storage
      if: always()
      run: |
        az storage blob upload-batch -s blob-report/resources -d '$web/run-${{ github.run_id }}/resources' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: blob-report
        path: blob-report/*.jsonl
        retention-days: 30

  merge-reports:
    if: ${{ always() }}
    needs: [test]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: npm ci

    - name: Download Blob Reports
      uses: actions/download-artifact@v2
      with:
        name: blob-report
        path: blob-report

    - name: Merge into HTML Report
      run: |
        npx playwright merge-reports --reporter html --attachments missing blob-report

    - name: Upload HTML Report to Azure Blob Storage
      run: |
        az storage blob upload-batch -s playwright-report -d '$web/run-${{ github.run_id }}' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"
        echo "Report url: https://pwblobreport01.z1.web.core.windows.net/run-${{ github.run_id }}/index.html"
