name: Publish Test Results
on:
  workflow_run:
    workflows: ["Playwright Tests"]

jobs:
  merge-reports:
    permissions:
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Download Blob Reports
      uses: actions/download-artifact@v3
      with:
        name: blob-report
        path: blob-report

    - name: Merge into HTML Report
      run: |
        npx playwright merge-reports --reporter html --attachments missing blob-report

    - name: Upload HTML Report to Azure Blob Storage
      run: |
        az storage blob upload-batch -s playwright-report -d '$web/run-pr-${{ github.run_id }}-${{ github.sha }}' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"
        az storage blob upload-batch -s blob-report -d '$web/run-pr-${{ github.run_id }}-${{ github.sha }}' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"
        echo "Report url: https://pwblobreport01.z1.web.core.windows.net/run-pr-${{ github.run_id }}-${{ github.sha }}/index.html"

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            ...context.repo,
            commit_sha: context.sha,
          });
          if (prs.length === 0) {
            core.error('No pull request found for commit ' + context.sha);
            return;
          }
          const reportUrl = `https://pwblobreport01.z1.web.core.windows.net/run-pr-${{ github.run_id }}-${{ github.sha }}/index.html`;
          core.notice('Report url: ' + reportUrl);
          const { data: response } = await github.rest.issues.createComment({
            ...context.repo,
            issue_number: prs[0].number,
            body: 'Pull request test results: ' + reportUrl,
          });
          core.info('Posted comment: ' + response.html_url);
