name: Publish Test Results
on:
  workflow_run:
    workflows: ["Playwright Tests"]

jobs:
  merge-reports:
    permissions:
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Download blob report
      uses: actions/github-script@v6
      with:
        script: |
          console.log(`downloading artifacts for ${context.payload.workflow_run.id}`);
          const { data } = await github.rest.actions.listWorkflowRunArtifacts({
            ...repo,
            run_id: context.payload.workflow_run.id
          });
          console.log('total = ', data.total_count);
          const name = 'blob-report';
          const report = data.artifacts.filter(a => a.name === name)[0];
          const result = await github.rest.actions.downloadArtifact({
            ...repo,
            artifact_id: report.id,
            archive_format: 'zip'
          });
          console.log('download result', result);
          const fs = require('fs');
          fs.writeFileSync(`${name}.zip`, Buffer.from(result.data));

    - name: Unzip blob report
      run: unzip blob-report.zip -d blob-report

    - name: Merge into HTML Report
      run: |
        npx playwright merge-reports --reporter html --attachments missing blob-report

    - name: Upload HTML Report to Azure Blob Storage
      run: |
        az storage blob upload-batch -s playwright-report -d '$web/run-pr-${{ github.run_id }}-${{ github.sha }}' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"
        az storage blob upload-batch -s blob-report -d '$web/run-pr-${{ github.run_id }}-${{ github.sha }}' --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}"
        echo "Report url: https://pwblobreport01.z1.web.core.windows.net/run-pr-${{ github.run_id }}-${{ github.sha }}/index.html"

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            ...context.repo,
            commit_sha: context.sha,
          });
          if (prs.length === 0) {
            core.error('No pull request found for commit ' + context.sha);
            return;
          }
          const reportUrl = `https://pwblobreport01.z1.web.core.windows.net/run-pr-${{ github.run_id }}-${{ github.sha }}/index.html`;
          core.notice('Report url: ' + reportUrl);
          const { data: response } = await github.rest.issues.createComment({
            ...context.repo,
            issue_number: prs[0].number,
            body: 'Pull request test results: ' + reportUrl,
          });
          core.info('Posted comment: ' + response.html_url);
